import { ThemeType } from '../types/ThemeType';

export const themes: ITheme[] = [
  {
    themeType: ThemeType.PINK,
    previewColors: ['#FBFBFB', '#FF0054'],
    colors: {
      backgroundColor: '#FBFBFB',
      boxColor: '#FFFFFF',
      hoverColor: 'rgba(0, 0, 0, 0.045)',
      textColor: '#FF0054',
      boxShadowColor: 'rgba(0, 0, 0, 0.12)',
      mainButtonTextColor: '#FFFFFF',
      mainButtonBgColor: '#FF0054',
      mainButtonShadowColor: '#DE1457',
      secondaryButtonTextColor: '#FF0054',
      secondaryButtonBgColor: '#ffffff',
      secondaryButtonShadowColor: 'rgba(0, 0, 0, 0.10)',
      dangerButtonTextColor: '',
      dangerButtonBgColor: '',
      dangerButtonShadowColor: '',
      commonColor: '#6C52B7',
      whiteColor: '#FFFFFF',
      secondaryColor: '#FF0054',
      progressBarColor: '#f3f3f3',
      questionTextColor: '#000000',
      duelCongratulationsBackground: '#007F5F',
      duelCongratulationsButtonColor: '#007F5F',
      scrollBarColor: 'rgba(0, 0, 0, .2)',
    },
  },
  {
    themeType: ThemeType.PURPLE,
    previewColors: ['#FBFBFB', '#6C63FF'],
    colors: {
      backgroundColor: '#FBFBFB',
      boxColor: '#FFFFFF',
      hoverColor: 'rgba(0, 0, 0, 0.045)',
      textColor: '#6C63FF',
      boxShadowColor: 'rgba(0, 0, 0, 0.12)',
      mainButtonTextColor: '#FFFFFF',
      mainButtonBgColor: '#6C63FF',
      mainButtonShadowColor: '#4138C7',
      secondaryButtonTextColor: '#6C63FF',
      secondaryButtonBgColor: '#ffffff',
      secondaryButtonShadowColor: 'rgba(0, 0, 0, 0.10)',
      dangerButtonTextColor: '',
      dangerButtonBgColor: '',
      dangerButtonShadowColor: '',
      commonColor: '#B752B3',
      whiteColor: '#FFFFFF',
      secondaryColor: '#6C63FF',
      progressBarColor: '',
      questionTextColor: '#000000',
      duelCongratulationsBackground: '#007F5F',
      duelCongratulationsButtonColor: '#007F5F',
      scrollBarColor: 'rgba(0, 0, 0, .2)',
    },
  },
  {
    themeType: ThemeType.BLUE,
    previewColors: ['#FBFBFB', '#126699'],
    colors: {
      backgroundColor: '#FBFBFB',
      boxColor: '#FFFFFF',
      hoverColor: 'rgba(0, 0, 0, 0.045)',
      textColor: '#126699',
      boxShadowColor: 'rgba(0, 0, 0, 0.28)',
      mainButtonTextColor: '',
      mainButtonBgColor: '',
      mainButtonShadowColor: '',
      secondaryButtonTextColor: '126699',
      secondaryButtonBgColor: '#ffffff',
      secondaryButtonShadowColor: 'rgba(0, 0, 0, 0.10)',
      dangerButtonTextColor: '',
      dangerButtonBgColor: '',
      dangerButtonShadowColor: '',
      commonColor: '#52b788',
      whiteColor: '#FFFFFF',
      secondaryColor: '#00509d',
      progressBarColor: '',
      questionTextColor: '#000000',
      duelCongratulationsBackground: '#007F5F',
      duelCongratulationsButtonColor: '#007F5F',
      scrollBarColor: 'rgba(0, 0, 0, .2)',
    },
  },
  {
    themeType: ThemeType.GREEN,
    previewColors: ['#FBFBFB', '#007f5f'],
    colors: {
      backgroundColor: '#FBFBFB',
      boxColor: '#FFFFFF',
      hoverColor: 'rgba(0, 0, 0, 0.045)',
      textColor: '#007f5f',
      boxShadowColor: 'rgba(0, 0, 0, 0.28)',
      mainButtonTextColor: '',
      mainButtonBgColor: '',
      mainButtonShadowColor: '',
      secondaryButtonTextColor: '',
      secondaryButtonBgColor: '',
      secondaryButtonShadowColor: '',
      dangerButtonTextColor: '',
      dangerButtonBgColor: '',
      dangerButtonShadowColor: '',
      commonColor: '#66B752',
      whiteColor: '#FFFFFF',
      secondaryColor: '#007f5f',
      progressBarColor: '',
      questionTextColor: '#000000',
      duelCongratulationsBackground: '#007F5F',
      duelCongratulationsButtonColor: '#007F5F',
      scrollBarColor: 'rgba(0, 0, 0, .2)',
    },
  },
  {
    themeType: ThemeType.RED,
    previewColors: ['#FBFBFB', '#ba181b'],
    colors: {
      backgroundColor: '#FBFBFB',
      boxColor: '#FFFFFF',
      hoverColor: 'rgba(0, 0, 0, 0.045)',
      textColor: '#ba181b',
      boxShadowColor: 'rgba(0, 0, 0, 0.28)',
      mainButtonTextColor: '',
      mainButtonBgColor: '',
      mainButtonShadowColor: '',
      secondaryButtonTextColor: '',
      secondaryButtonBgColor: '',
      secondaryButtonShadowColor: '',
      dangerButtonTextColor: '',
      dangerButtonBgColor: '',
      dangerButtonShadowColor: '',
      commonColor: '#B78F52',
      whiteColor: '#FFFFFF',
      secondaryColor: '#ba181b',
      progressBarColor: '',
      questionTextColor: '#000000',
      duelCongratulationsBackground: '#007F5F',
      duelCongratulationsButtonColor: '#007F5F',
      scrollBarColor: 'rgba(0, 0, 0, .2)',
    },
  },
  {
    themeType: ThemeType.DARK,
    previewColors: ['#212121', '#E5E5E5'],
    colors: {
      backgroundColor: '#212121',
      boxColor: '#3C3C3C',
      hoverColor: 'rgba(255, 255, 255, 0.2)',
      textColor: '#E5E5E5',
      boxShadowColor: 'rgba(255, 255, 255, 0.4)',
      mainButtonTextColor: '',
      mainButtonBgColor: '',
      mainButtonShadowColor: '',
      secondaryButtonTextColor: '',
      secondaryButtonBgColor: '',
      secondaryButtonShadowColor: '',
      dangerButtonTextColor: '',
      dangerButtonBgColor: '',
      dangerButtonShadowColor: '',
      commonColor: '#4E4E4E',
      whiteColor: '#E5E5E5',
      secondaryColor: '#4E4E4E',
      progressBarColor: '',
      questionTextColor: '#E5E5E5',
      duelCongratulationsBackground: '#212121',
      duelCongratulationsButtonColor: '#E5E5E5',
      scrollBarColor: 'rgba(255, 255, 255, .2)',
    },
  },
  {
    themeType: ThemeType.DARK_PURPLE,
    previewColors: ['#212121', '#6C63FF'],
    colors: {
      backgroundColor: '#212121',
      boxColor: '#2C2C2C',
      hoverColor: 'rgba(255, 255, 255, 0.2)',
      textColor: '#E5E5E5',
      boxShadowColor: 'rgba(0, 0, 0, 0.5)',
      mainButtonTextColor: '#FFFFFF',
      mainButtonBgColor: '#6C63FF',
      mainButtonShadowColor: '#4138C7',
      secondaryButtonTextColor: '#E5E5E5',
      secondaryButtonBgColor: '#2C2C2C',
      secondaryButtonShadowColor: 'rgba(0, 0, 0, 0.25)',
      dangerButtonTextColor: '',
      dangerButtonBgColor: '',
      dangerButtonShadowColor: '',
      commonColor: '#4E4E4E',
      whiteColor: '#E5E5E5',
      secondaryColor: '#4E4E4E',
      progressBarColor: '#414141',
      questionTextColor: '#E5E5E5',
      duelCongratulationsBackground: '#212121',
      duelCongratulationsButtonColor: '#E5E5E5',
      scrollBarColor: 'rgba(255, 255, 255, .2)',
    },
  },
  {
    themeType: ThemeType.DARK_GREEN,
    previewColors: ['#212121', '#E5E5E5'],
    colors: {
      backgroundColor: '#212121',
      boxColor: '#3C3C3C',
      hoverColor: 'rgba(255, 255, 255, 0.2)',
      textColor: '#E5E5E5',
      boxShadowColor: 'rgba(255, 255, 255, 0.4)',
      mainButtonTextColor: '',
      mainButtonBgColor: '',
      mainButtonShadowColor: '',
      secondaryButtonTextColor: '',
      secondaryButtonBgColor: '',
      secondaryButtonShadowColor: '',
      dangerButtonTextColor: '',
      dangerButtonBgColor: '',
      dangerButtonShadowColor: '',
      commonColor: '#4E4E4E',
      whiteColor: '#E5E5E5',
      secondaryColor: '#4E4E4E',
      progressBarColor: '',
      questionTextColor: '#E5E5E5',
      duelCongratulationsBackground: '#212121',
      duelCongratulationsButtonColor: '#E5E5E5',
      scrollBarColor: 'rgba(255, 255, 255, .2)',
    },
  },
  {
    themeType: ThemeType.DARK_PINK,
    previewColors: ['#212121', '#E5E5E5'],
    colors: {
      backgroundColor: '#212121',
      boxColor: '#3C3C3C',
      hoverColor: 'rgba(255, 255, 255, 0.2)',
      textColor: '#E5E5E5',
      boxShadowColor: 'rgba(255, 255, 255, 0.4)',
      mainButtonTextColor: '',
      mainButtonBgColor: '',
      mainButtonShadowColor: '',
      secondaryButtonTextColor: '',
      secondaryButtonBgColor: '',
      secondaryButtonShadowColor: '',
      dangerButtonTextColor: '',
      dangerButtonBgColor: '',
      dangerButtonShadowColor: '',
      commonColor: '#4E4E4E',
      whiteColor: '#E5E5E5',
      secondaryColor: '#4E4E4E',
      progressBarColor: '',
      questionTextColor: '#E5E5E5',
      duelCongratulationsBackground: '#212121',
      duelCongratulationsButtonColor: '#E5E5E5',
      scrollBarColor: 'rgba(255, 255, 255, .2)',
    },
  },
];
