import { ITheme } from '../interfaces/ITheme';
import { ThemeType } from '../types/ThemeType';

export const themes: ITheme[] = [
  {
    themeType: ThemeType.PINK,
    previewColor: '#D915B9',
    colors: {
      backgroundColor: '#fcfcfc',
      boxColor: '#FFFFFF',
      hoverColor: 'rgba(0, 0, 0, 0.045)',
      textColor: '#D915B9',
      boxShadowColor: 'rgba(0, 0, 0, 0.4)',
      commonColor: '#6C52B7',
      whiteColor: '#FFFFFF',
      secondaryColor: '#D915B9',
      questionTextColor: '#000000',
      duelCongratulationsBackground: '#007F5F',
      duelCongratulationsButtonColor: '#007F5F',
      scrollBarColor: 'rgba(0, 0, 0, .2)',
    },
  },
  {
    themeType: ThemeType.PURPLE,
    previewColor: '#6B17CD',
    colors: {
      backgroundColor: '#fcfcfc',
      boxColor: '#FFFFFF',
      hoverColor: 'rgba(0, 0, 0, 0.045)',
      textColor: '#6B17CD',
      boxShadowColor: 'rgba(0, 0, 0, 0.4)',
      commonColor: '#B752B3',
      whiteColor: '#FFFFFF',
      secondaryColor: '#6B17CD',
      questionTextColor: '#000000',
      duelCongratulationsBackground: '#007F5F',
      duelCongratulationsButtonColor: '#007F5F',
      scrollBarColor: 'rgba(0, 0, 0, .2)',
    },
  },
  {
    themeType: ThemeType.BLUE,
    previewColor: '#126699',
    colors: {
      backgroundColor: '#fcfcfc',
      boxColor: '#FFFFFF',
      hoverColor: 'rgba(0, 0, 0, 0.045)',
      textColor: '#126699',
      boxShadowColor: 'rgba(0, 0, 0, 0.4)',
      commonColor: '#52b788',
      whiteColor: '#FFFFFF',
      secondaryColor: '#00509d',
      questionTextColor: '#000000',
      duelCongratulationsBackground: '#007F5F',
      duelCongratulationsButtonColor: '#007F5F',
      scrollBarColor: 'rgba(0, 0, 0, .2)',
    },
  },
  {
    themeType: ThemeType.GREEN,
    previewColor: '#007f5f',
    colors: {
      backgroundColor: '#fcfcfc',
      boxColor: '#FFFFFF',
      hoverColor: 'rgba(0, 0, 0, 0.045)',
      textColor: '#007f5f',
      boxShadowColor: 'rgba(0, 0, 0, 0.4)',
      commonColor: '#66B752',
      whiteColor: '#FFFFFF',
      secondaryColor: '#007f5f',
      questionTextColor: '#000000',
      duelCongratulationsBackground: '#007F5F',
      duelCongratulationsButtonColor: '#007F5F',
      scrollBarColor: 'rgba(0, 0, 0, .2)',
    },
  },
  {
    themeType: ThemeType.RED,
    previewColor: '#ba181b',
    colors: {
      backgroundColor: '#fcfcfc',
      boxColor: '#FFFFFF',
      hoverColor: 'rgba(0, 0, 0, 0.045)',
      textColor: '#ba181b',
      boxShadowColor: 'rgba(0, 0, 0, 0.4)',
      commonColor: '#B78F52',
      whiteColor: '#FFFFFF',
      secondaryColor: '#ba181b',
      questionTextColor: '#000000',
      duelCongratulationsBackground: '#007F5F',
      duelCongratulationsButtonColor: '#007F5F',
      scrollBarColor: 'rgba(0, 0, 0, .2)',
    },
  },
  {
    themeType: ThemeType.DARK,
    previewColor: '#212121',
    colors: {
      backgroundColor: '#212121',
      boxColor: '#3C3C3C',
      hoverColor: 'rgba(255, 255, 255, 0.2)',
      textColor: '#E5E5E5',
      boxShadowColor: 'rgba(255, 255, 255, 0.4)',
      commonColor: '#4E4E4E',
      whiteColor: '#E5E5E5',
      secondaryColor: '#4E4E4E',
      questionTextColor: '#E5E5E5',
      duelCongratulationsBackground: '#212121',
      duelCongratulationsButtonColor: '#E5E5E5',
      scrollBarColor: 'rgba(255, 255, 255, .2)',
    },
  },
];
