import { ThemeType } from '../types/ThemeType';

const fontsSize = {
  computer: '2.25vh',
  tablet: '2.2vw',
  smartphone: '3.3vw',
  smallFonts: {
    computer: '2vh',
    tablet: '2vw',
    smartphone: '3vw',
  },
};

const similarColors = {
  warningColor: '#CB0000',
  rightQuestion: '#52b788',
  wrongQuestion: '#f72585',
  skippedQuestion: '#a100f2',
};

export const themes: ITheme[] = [
  {
    themeType: ThemeType.LIGHT_PINK,
    previewColors: ['#FBFBFB', '#FF0054'],
    colors: {
      backgroundColor: '#FBFBFB',
      boxColor: '#FFFFFF',
      hoverColor: '#F1F1F1',
      textColor: '#FF0054',
      boxShadowColor: 'rgba(0, 0, 0, 0.12)',
      mainButtonTextColor: '#FFFFFF',
      mainButtonBgColor: '#FF0054',
      mainButtonShadowColor: '#DE1457',
      secondaryButtonTextColor: '#FF0054',
      secondaryButtonBgColor: '#ffffff',
      secondaryButtonShadowColor: 'rgba(0, 0, 0, 0.10)',
      dangerButtonTextColor: '',
      dangerButtonBgColor: '',
      dangerButtonShadowColor: '',
      commonColor: '#6C63FF',
      whiteColor: '#FFFFFF',
      secondaryColor: '#FF0054',
      progressBarColor: '#f3f3f3',
      questionTextColor: '#000000',
      duelCongratulationsBackground: '#007F5F',
      duelCongratulationsButtonColor: '#007F5F',
      scrollBarColor: 'rgba(0, 0, 0, .2)',
      inputTextBgColor: '#F3F3F3',
    },
    fontsSize,
    similarColors,
  },
  {
    themeType: ThemeType.LIGHT_PURPLE,
    previewColors: ['#FBFBFB', '#6C63FF'],
    colors: {
      backgroundColor: '#FBFBFB',
      boxColor: '#FFFFFF',
      hoverColor: '#F1F1F1',
      textColor: '#6C63FF',
      boxShadowColor: 'rgba(0, 0, 0, 0.12)',
      mainButtonTextColor: '#FFFFFF',
      mainButtonBgColor: '#6C63FF',
      mainButtonShadowColor: '#4138C7',
      secondaryButtonTextColor: '#6C63FF',
      secondaryButtonBgColor: '#ffffff',
      secondaryButtonShadowColor: 'rgba(0, 0, 0, 0.10)',
      dangerButtonTextColor: '',
      dangerButtonBgColor: '',
      dangerButtonShadowColor: '',
      commonColor: '#B752B3',
      whiteColor: '#FFFFFF',
      secondaryColor: '#6C63FF',
      progressBarColor: '#F2F2F2',
      questionTextColor: '#000000',
      duelCongratulationsBackground: '#007F5F',
      duelCongratulationsButtonColor: '#007F5F',
      scrollBarColor: 'rgba(0, 0, 0, .2)',
      inputTextBgColor: '#F3F3F3',
    },
    fontsSize,
    similarColors,
  },
  {
    themeType: ThemeType.LIGHT_BLUE,
    previewColors: ['#FBFBFB', '#126699'],
    colors: {
      backgroundColor: '#FBFBFB',
      boxColor: '#FFFFFF',
      hoverColor: '#F1F1F1',
      textColor: '#126699',
      boxShadowColor: 'rgba(0, 0, 0, 0.)',
      mainButtonTextColor: '#FFFFFF',
      mainButtonBgColor: '#126699',
      mainButtonShadowColor: '#0E3147',
      secondaryButtonTextColor: '#126699',
      secondaryButtonBgColor: '#ffffff',
      secondaryButtonShadowColor: 'rgba(0, 0, 0, 0.10)',
      dangerButtonTextColor: '',
      dangerButtonBgColor: '',
      dangerButtonShadowColor: '',
      commonColor: '#52b788',
      whiteColor: '#FFFFFF',
      secondaryColor: '#00509d',
      progressBarColor: '#F2F2F2',
      questionTextColor: '#000000',
      duelCongratulationsBackground: '#007F5F',
      duelCongratulationsButtonColor: '#007F5F',
      scrollBarColor: 'rgba(0, 0, 0, .2)',
      inputTextBgColor: '#F3F3F3',
    },
    fontsSize,
    similarColors,
  },
  {
    themeType: ThemeType.LIGHT_GREEN,
    previewColors: ['#FBFBFB', '#007f5f'],
    colors: {
      backgroundColor: '#FBFBFB',
      boxColor: '#FFFFFF',
      hoverColor: '#F1F1F1',
      textColor: '#007f5f',
      boxShadowColor: 'rgba(0, 0, 0, 0.15)',
      mainButtonTextColor: '#FFFFFF',
      mainButtonBgColor: '#007f5f',
      mainButtonShadowColor: '#005A44',
      secondaryButtonTextColor: '#007f5f',
      secondaryButtonBgColor: '#ffffff',
      secondaryButtonShadowColor: 'rgba(0, 0, 0, 0.10)',
      dangerButtonTextColor: '',
      dangerButtonBgColor: '',
      dangerButtonShadowColor: '',
      commonColor: '#66B752',
      whiteColor: '#FFFFFF',
      secondaryColor: '#007f5f',
      progressBarColor: '#F2F2F2',
      questionTextColor: '#000000',
      duelCongratulationsBackground: '#007F5F',
      duelCongratulationsButtonColor: '#007F5F',
      scrollBarColor: 'rgba(0, 0, 0, .2)',
      inputTextBgColor: '#F3F3F3',
    },
    fontsSize,
    similarColors,
  },
  {
    themeType: ThemeType.LIGHT_RED,
    previewColors: ['#FBFBFB', '#d90429'],
    colors: {
      backgroundColor: '#FBFBFB',
      boxColor: '#FFFFFF',
      hoverColor: '#F1F1F1',
      textColor: '#d90429',
      boxShadowColor: 'rgba(0, 0, 0, 0.)',
      mainButtonTextColor: '#FFFFFF',
      mainButtonBgColor: '#d90429',
      mainButtonShadowColor: '',
      secondaryButtonTextColor: '#d90429',
      secondaryButtonBgColor: '#ffffff',
      secondaryButtonShadowColor: 'rgba(0, 0, 0, 0.10)',
      dangerButtonTextColor: '',
      dangerButtonBgColor: '',
      dangerButtonShadowColor: '',
      commonColor: '#B78F52',
      whiteColor: '#FFFFFF',
      secondaryColor: '#d90429',
      progressBarColor: '#F2F2F2',
      questionTextColor: '#000000',
      duelCongratulationsBackground: '#007F5F',
      duelCongratulationsButtonColor: '#007F5F',
      scrollBarColor: 'rgba(0, 0, 0, .2)',
      inputTextBgColor: '#F3F3F3',
    },
    fontsSize,
    similarColors,
  },
  {
    themeType: ThemeType.DARK_WHITE,
    previewColors: ['#212121', '#E5E5E5'],
    colors: {
      backgroundColor: '#212121',
      boxColor: '#3C3C3C',
      hoverColor: '#333333',
      textColor: '#E5E5E5',
      boxShadowColor: 'rgba(255, 255, 255, 0.4)',
      mainButtonTextColor: '',
      mainButtonBgColor: '',
      mainButtonShadowColor: '',
      secondaryButtonTextColor: '',
      secondaryButtonBgColor: '',
      secondaryButtonShadowColor: '',
      dangerButtonTextColor: '',
      dangerButtonBgColor: '',
      dangerButtonShadowColor: '',
      commonColor: '#212121',
      whiteColor: '#E5E5E5',
      secondaryColor: '#212121',
      progressBarColor: '#F2F2F2',
      questionTextColor: '#E5E5E5',
      duelCongratulationsBackground: '#212121',
      duelCongratulationsButtonColor: '#E5E5E5',
      scrollBarColor: 'rgba(255, 255, 255, .2)',
      inputTextBgColor: '#333333',
    },
    fontsSize,
    similarColors,
  },
  {
    themeType: ThemeType.DARK_PINK,
    previewColors: ['#212121', '#FF0054'],
    colors: {
      backgroundColor: '#212121',
      boxColor: '#2C2C2C',
      hoverColor: '#333333',
      textColor: '#FFFFFF',
      boxShadowColor: 'rgba(0, 0, 0, 0.5)',
      mainButtonTextColor: '#FFFFFF',
      mainButtonBgColor: '#FF0054',
      mainButtonShadowColor: '#DE1457',
      secondaryButtonTextColor: '#FFFFFF',
      secondaryButtonBgColor: '#2C2C2C',
      secondaryButtonShadowColor: 'rgba(0, 0, 0, 0.25)',
      dangerButtonTextColor: '',
      dangerButtonBgColor: '',
      dangerButtonShadowColor: '',
      commonColor: '#212121',
      whiteColor: '#FFFFFF',
      secondaryColor: '#212121',
      progressBarColor: '#414141',
      questionTextColor: '#FFFFFF',
      duelCongratulationsBackground: '#212121',
      duelCongratulationsButtonColor: '#FFFFFF',
      scrollBarColor: 'rgba(255, 255, 255, .2)',
      inputTextBgColor: '#333333',
    },
    fontsSize,
    similarColors,
  },
  {
    themeType: ThemeType.DARK_PURPLE,
    previewColors: ['#2C2C2C', '#6C63FF'],
    colors: {
      backgroundColor: '#212121',
      boxColor: '#2C2C2C',
      hoverColor: '#333333',
      textColor: '#E5E5E5',
      boxShadowColor: 'rgba(0, 0, 0, 0.5)',
      mainButtonTextColor: '#FFFFFF',
      mainButtonBgColor: '#6C63FF',
      mainButtonShadowColor: '#4138C7',
      secondaryButtonTextColor: '#E5E5E5',
      secondaryButtonBgColor: '#2C2C2C',
      secondaryButtonShadowColor: 'rgba(0, 0, 0, 0.25)',
      dangerButtonTextColor: '',
      dangerButtonBgColor: '',
      dangerButtonShadowColor: '',
      commonColor: '#212121',
      whiteColor: '#E5E5E5',
      secondaryColor: '#212121',
      progressBarColor: '#414141',
      questionTextColor: '#E5E5E5',
      duelCongratulationsBackground: '#212121',
      duelCongratulationsButtonColor: '#E5E5E5',
      scrollBarColor: 'rgba(255, 255, 255, .2)',
      inputTextBgColor: '#333333',
    },
    fontsSize,
    similarColors,
  },
  {
    themeType: ThemeType.DARK_GREEN,
    previewColors: ['#212121', '#E5E5E5'],
    colors: {
      backgroundColor: '#212121',
      boxColor: '#3C3C3C',
      hoverColor: '#333333',
      textColor: '#E5E5E5',
      boxShadowColor: 'rgba(255, 255, 255, 0.4)',
      mainButtonTextColor: '',
      mainButtonBgColor: '',
      mainButtonShadowColor: '',
      secondaryButtonTextColor: '',
      secondaryButtonBgColor: '',
      secondaryButtonShadowColor: '',
      dangerButtonTextColor: '',
      dangerButtonBgColor: '',
      dangerButtonShadowColor: '',
      commonColor: '#212121',
      whiteColor: '#E5E5E5',
      secondaryColor: '#212121',
      progressBarColor: '#414141',
      questionTextColor: '#E5E5E5',
      duelCongratulationsBackground: '#212121',
      duelCongratulationsButtonColor: '#E5E5E5',
      scrollBarColor: 'rgba(255, 255, 255, .2)',
      inputTextBgColor: '#333333',
    },
    fontsSize,
    similarColors,
  },
];
